/**
 * Service Worker registration.
 * The actual SW is generated by vite-plugin-pwa (workbox).
 */
export function registerServiceWorker() {
  if ('serviceWorker' in navigator && import.meta.env.PROD) {
    window.addEventListener('load', () => {
      navigator.serviceWorker
        .register('/sw.js')
        .then((reg) => {
          console.log('[SW] Registered:', reg.scope)
          reg.addEventListener('updatefound', () => {
            const newWorker = reg.installing
            if (!newWorker) return
            newWorker.addEventListener('statechange', () => {
              if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                console.log('[SW] New content available. Refresh to update.')
              }
            })
          })
        })
        .catch((err) => console.warn('[SW] Registration failed:', err))
    })
  }
}
